name: Publish reflex-altair

on:
  push:
    tags:
      - "altair-v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
      contents: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Set up Python
        run: uv python install

      - name: Build package
        run: |
          cd altair
          uv build

      - name: Publish to PyPI
        run: |
          cd altair
          uv publish
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_ALTAIR_TOKEN }}

